### ISSUE TITLE
Version 18.7.2: The box you're attempting to add has no available version that matches the constraints you requested.

### ISSUE THREAD

**Issue by rudibroekhuizen** [EugenMayer/packer-opnsense#4]
I am trying to start version 18.7.2 of OPNsense using your vagrant box from vagrantcloud.com. I receive the following message if I do a vagrant up opnsense. My Vagrantfile looks like this:

```
Vagrant.configure("2") do |config|
  config.vm.box = "eugenmayer/opnsense"
  config.vm.box_version = "18.7.2"
end
```

Bringing machine 'opnsense' up with 'virtualbox' provider...
==> opnsense: Box 'eugenmayer/opnsense' could not be found. Attempting to find and install...
    opnsense: Box Provider: virtualbox
    opnsense: Box Version: 18.7.2
==> opnsense: Loading metadata for box 'eugenmayer/opnsense'
    opnsense: URL: https://vagrantcloud.com/eugenmayer/opnsense
The box you're attempting to add has no available version that
matches the constraints you requested. Please double-check your
settings. Also verify that if you specified version constraints,
that the provider you wish to use is available for these constraints.

Box: eugenmayer/opnsense
Address: https://vagrantcloud.com/eugenmayer/opnsense
Constraints: 18.7.2
Available versions: 18.1.1.pre.build1

Is this image available, of am I doing something wrong?

**Comment by EugenMayer** [comment]
Sorry i forgot to press the "release version" on vargant cloud..and since i was logged in it worked for me.

Should be working now :)

https://app.vagrantup.com/eugenmayer/boxes/opnsense
