### ISSUE TITLE
Save interface settings in .box

### ISSUE THREAD

**Issue by rudibroekhuizen** [EugenMayer/packer-opnsense#6]
I build an Vagrant .ovf set with opnsense.json. After that I import the machine into Virtualbox. I can see two interfaces, as configured in opnsense.json.

With  **vagrant package --base opnsense** I want to convert it to the .box format, to be able to use it in Vagrantcloud. For some reason the interface settings disappear, only one interfaces shows up after booting a machine using the .box format, while two interfaces are configured in the .ovf file.  

I don't understand who the network config is different after converting to .box format.

**Comment by EugenMayer** [comment]
sorry I cannot help you with that

**Comment by rudibroekhuizen** [comment]
I will look at it, thanks.
